print("What is your name?")
name = input()
print(name)

print("What is your email?")
email = input()
print(email)

print("What is your ORG?")
ORG = input()
print(ORG)

print("What is your access level?")
access = input()
print(access)

print("+-------------------------------------------------------+")
print("|               APEX ENTERTAINMENT PASS                 |")
print("|-------------------------------------------------------|")
print("| ATTENDEE    : " + name.ljust(32) + "        |")
print("| ORG         :"  + ORG.ljust(33)  + "        |")
print("| CONTACT     :" + email.ljust(33) + "        |")
print("| Access Level:" + access.ljust(34) + "       |")
print("| Issuer      :   BCH SOFTWARE TEMINAL SYSTEM           |")
print("+-------------------------------------------------------+")