print("What is your name?")
name = input()
print(name)

print("What is your email?")
email = input()
print(email)

print("What is your ORG?")
ORG = input()
print(ORG)

print("What is your access level?")
access = input()
print(access)

print("+--------------------------------------------------+")
print("|               APEX ENTERTAINMENT PASS            |")
print("|--------------------------------------------------|")
print("| ATTENDEE : " + name.ljust(29) + "         |")
print("| ORG      :"  + ORG.ljust(30)  + "         |")
print("| CONTACT  :" + email.ljust(30) + "         |")
print("| Access Level:" + access.ljust(31) + "     |")
print("| Issuer   : BCH SOFTWARE TEMINAL SYSTEM           |")
print("+--------------------------------------------------+")