print("What is your name?")
name = input()
print(name)
print("What is your email?")
email = input()
print(email)
ORG = input()
print("+---------------------------------+")
print("|    APEX ENTERTAINMENT PASS      |")
print("|---------------------------------|")
print("| ATTENDEE : " + name.ljust(12) + "         |")
print("| ORG      :")